//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditTalk
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/WCCrivo", ConfigurationName="CreditTalk.CreditTalkStatelessSoap")]
    public interface CreditTalkStatelessSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCCrivo/Report", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditTalk.ReportResponse> ReportAsync(CreditTalk.ReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCCrivo/Explain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditTalk.ExplainResponse> ExplainAsync(CreditTalk.ExplainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCCrivo/LoadPDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditTalk.LoadPDFResponse> LoadPDFAsync(CreditTalk.LoadPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCCrivo/Values", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditTalk.ValuesResponse> ValuesAsync(CreditTalk.ValuesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCCrivo/Layout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditTalk.LayoutResponse> LayoutAsync(CreditTalk.LayoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCCrivo/Parameters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditTalk.ParametersResponse> ParametersAsync(CreditTalk.ParametersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCCrivo/RawData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditTalk.RawDataResponse> RawDataAsync(CreditTalk.RawDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCCrivo/Sources", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditTalk.SourcesResponse> SourcesAsync(CreditTalk.SourcesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCCrivo/LoadLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditTalk.LoadLogResponse> LoadLogAsync(CreditTalk.LoadLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCCrivo/Eval", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditTalk.EvalResponse> EvalAsync(CreditTalk.EvalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCCrivo/SetPolicyEval", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditTalk.SetPolicyEvalResponse> SetPolicyEvalAsync(CreditTalk.SetPolicyEvalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCCrivo/SetPolicyEvalValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditTalk.SetPolicyEvalValuesResponse> SetPolicyEvalValuesAsync(CreditTalk.SetPolicyEvalValuesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCCrivo/SetPolicyEvalValuesXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditTalk.SetPolicyEvalValuesXmlResponse> SetPolicyEvalValuesXmlAsync(CreditTalk.SetPolicyEvalValuesXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCCrivo/SetPolicyEvalValuesObjectXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditTalk.SetPolicyEvalValuesObjectXmlResponse> SetPolicyEvalValuesObjectXmlAsync(CreditTalk.SetPolicyEvalValuesObjectXmlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Report", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class ReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string sUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=1)]
        public string sPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=2)]
        public string sOperacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=3)]
        public string sDriver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=4)]
        public string sProduto;
        
        public ReportRequest()
        {
        }
        
        public ReportRequest(string sUser, string sPassword, string sOperacao, string sDriver, string sProduto)
        {
            this.sUser = sUser;
            this.sPassword = sPassword;
            this.sOperacao = sOperacao;
            this.sDriver = sDriver;
            this.sProduto = sProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReportResponse", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class ReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string ReportResult;
        
        public ReportResponse()
        {
        }
        
        public ReportResponse(string ReportResult)
        {
            this.ReportResult = ReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Explain", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class ExplainRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string sUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=1)]
        public string sPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=2)]
        public string sOperacao;
        
        public ExplainRequest()
        {
        }
        
        public ExplainRequest(string sUser, string sPassword, string sOperacao)
        {
            this.sUser = sUser;
            this.sPassword = sPassword;
            this.sOperacao = sOperacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExplainResponse", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class ExplainResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string ExplainResult;
        
        public ExplainResponse()
        {
        }
        
        public ExplainResponse(string ExplainResult)
        {
            this.ExplainResult = ExplainResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadPDF", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class LoadPDFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string sUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=1)]
        public string sPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=2)]
        public string sOperacao;
        
        public LoadPDFRequest()
        {
        }
        
        public LoadPDFRequest(string sUser, string sPassword, string sOperacao)
        {
            this.sUser = sUser;
            this.sPassword = sPassword;
            this.sOperacao = sOperacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadPDFResponse", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class LoadPDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] LoadPDFResult;
        
        public LoadPDFResponse()
        {
        }
        
        public LoadPDFResponse(byte[] LoadPDFResult)
        {
            this.LoadPDFResult = LoadPDFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Values", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class ValuesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string sUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=1)]
        public string sPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=2)]
        public string sOperacao;
        
        public ValuesRequest()
        {
        }
        
        public ValuesRequest(string sUser, string sPassword, string sOperacao)
        {
            this.sUser = sUser;
            this.sPassword = sPassword;
            this.sOperacao = sOperacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValuesResponse", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class ValuesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string ValuesResult;
        
        public ValuesResponse()
        {
        }
        
        public ValuesResponse(string ValuesResult)
        {
            this.ValuesResult = ValuesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Layout", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class LayoutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string sUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=1)]
        public string sPassword;
        
        public LayoutRequest()
        {
        }
        
        public LayoutRequest(string sUser, string sPassword)
        {
            this.sUser = sUser;
            this.sPassword = sPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayoutResponse", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class LayoutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string LayoutResult;
        
        public LayoutResponse()
        {
        }
        
        public LayoutResponse(string LayoutResult)
        {
            this.LayoutResult = LayoutResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/WCCrivo")]
    public partial class Parametro
    {
        
        private string nomeField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.crivo.com.br")]
    public partial class ResultVariavelXml
    {
        
        private string nomeField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.crivo.com.br")]
    public partial class ResultProdutoXml
    {
        
        private string nomeField;
        
        private ResultVariavelXml[] variaveisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Variavel")]
        public ResultVariavelXml[] Variaveis
        {
            get
            {
                return this.variaveisField;
            }
            set
            {
                this.variaveisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.crivo.com.br")]
    public partial class ResultDriverXml
    {
        
        private string nomeField;
        
        private ResultProdutoXml[] produtosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Produto")]
        public ResultProdutoXml[] Produtos
        {
            get
            {
                return this.produtosField;
            }
            set
            {
                this.produtosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.crivo.com.br")]
    public partial class ResultRespostasXml
    {
        
        private string sistemaField;
        
        private string criterioField;
        
        private string respostaField;
        
        private bool finalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sistema
        {
            get
            {
                return this.sistemaField;
            }
            set
            {
                this.sistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criterio
        {
            get
            {
                return this.criterioField;
            }
            set
            {
                this.criterioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Resposta
        {
            get
            {
                return this.respostaField;
            }
            set
            {
                this.respostaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Final
        {
            get
            {
                return this.finalField;
            }
            set
            {
                this.finalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.crivo.com.br")]
    public partial class ResultEvalValuesXml
    {
        
        private string codigoOperacaoField;
        
        private string[] operacoesObjetoAnaliseField;
        
        private ResultRespostasXml[] respostasField;
        
        private ResultDriverXml[] driversField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CodigoOperacao
        {
            get
            {
                return this.codigoOperacaoField;
            }
            set
            {
                this.codigoOperacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CodigoOperacao")]
        public string[] OperacoesObjetoAnalise
        {
            get
            {
                return this.operacoesObjetoAnaliseField;
            }
            set
            {
                this.operacoesObjetoAnaliseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Resposta")]
        public ResultRespostasXml[] Respostas
        {
            get
            {
                return this.respostasField;
            }
            set
            {
                this.respostasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Driver")]
        public ResultDriverXml[] Drivers
        {
            get
            {
                return this.driversField;
            }
            set
            {
                this.driversField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Parameters", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class ParametersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string sUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=1)]
        public string sPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=2)]
        public string sOperacao;
        
        public ParametersRequest()
        {
        }
        
        public ParametersRequest(string sUser, string sPassword, string sOperacao)
        {
            this.sUser = sUser;
            this.sPassword = sPassword;
            this.sOperacao = sOperacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParametersResponse", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class ParametersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public CreditTalk.Parametro[] ParametersResult;
        
        public ParametersResponse()
        {
        }
        
        public ParametersResponse(CreditTalk.Parametro[] ParametersResult)
        {
            this.ParametersResult = ParametersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RawData", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class RawDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string sUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=1)]
        public string sPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=2)]
        public string sOperacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=3)]
        public string sDriver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=4)]
        public string sProduto;
        
        public RawDataRequest()
        {
        }
        
        public RawDataRequest(string sUser, string sPassword, string sOperacao, string sDriver, string sProduto)
        {
            this.sUser = sUser;
            this.sPassword = sPassword;
            this.sOperacao = sOperacao;
            this.sDriver = sDriver;
            this.sProduto = sProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RawDataResponse", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class RawDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string[] RawDataResult;
        
        public RawDataResponse()
        {
        }
        
        public RawDataResponse(string[] RawDataResult)
        {
            this.RawDataResult = RawDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sources", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class SourcesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string sUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=1)]
        public string sPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=2)]
        public string sOperacao;
        
        public SourcesRequest()
        {
        }
        
        public SourcesRequest(string sUser, string sPassword, string sOperacao)
        {
            this.sUser = sUser;
            this.sPassword = sPassword;
            this.sOperacao = sOperacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SourcesResponse", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class SourcesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string SourcesResult;
        
        public SourcesResponse()
        {
        }
        
        public SourcesResponse(string SourcesResult)
        {
            this.SourcesResult = SourcesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadLog", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class LoadLogRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string sUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=1)]
        public string sPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=2)]
        public string sOperacao;
        
        public LoadLogRequest()
        {
        }
        
        public LoadLogRequest(string sUser, string sPassword, string sOperacao)
        {
            this.sUser = sUser;
            this.sPassword = sPassword;
            this.sOperacao = sOperacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadLogResponse", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class LoadLogResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string LoadLogResult;
        
        public LoadLogResponse()
        {
        }
        
        public LoadLogResponse(string LoadLogResult)
        {
            this.LoadLogResult = LoadLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Eval", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class EvalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string sUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=1)]
        public string sPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=2)]
        public string sParametros;
        
        public EvalRequest()
        {
        }
        
        public EvalRequest(string sUser, string sPassword, string sParametros)
        {
            this.sUser = sUser;
            this.sPassword = sPassword;
            this.sParametros = sParametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EvalResponse", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class EvalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string EvalResult;
        
        public EvalResponse()
        {
        }
        
        public EvalResponse(string EvalResult)
        {
            this.EvalResult = EvalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPolicyEval", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class SetPolicyEvalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string sUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=1)]
        public string sPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=2)]
        public string sPolitica;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=3)]
        public string sParametros;
        
        public SetPolicyEvalRequest()
        {
        }
        
        public SetPolicyEvalRequest(string sUser, string sPassword, string sPolitica, string sParametros)
        {
            this.sUser = sUser;
            this.sPassword = sPassword;
            this.sPolitica = sPolitica;
            this.sParametros = sParametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPolicyEvalResponse", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class SetPolicyEvalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string SetPolicyEvalResult;
        
        public SetPolicyEvalResponse()
        {
        }
        
        public SetPolicyEvalResponse(string SetPolicyEvalResult)
        {
            this.SetPolicyEvalResult = SetPolicyEvalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPolicyEvalValues", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class SetPolicyEvalValuesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string sUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=1)]
        public string sPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=2)]
        public string sPolitica;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=3)]
        public string sParametros;
        
        public SetPolicyEvalValuesRequest()
        {
        }
        
        public SetPolicyEvalValuesRequest(string sUser, string sPassword, string sPolitica, string sParametros)
        {
            this.sUser = sUser;
            this.sPassword = sPassword;
            this.sPolitica = sPolitica;
            this.sParametros = sParametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPolicyEvalValuesResponse", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class SetPolicyEvalValuesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string SetPolicyEvalValuesResult;
        
        public SetPolicyEvalValuesResponse()
        {
        }
        
        public SetPolicyEvalValuesResponse(string SetPolicyEvalValuesResult)
        {
            this.SetPolicyEvalValuesResult = SetPolicyEvalValuesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPolicyEvalValuesXml", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class SetPolicyEvalValuesXmlRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string sUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=1)]
        public string sPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=2)]
        public string sPolitica;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=3)]
        public string sParametros;
        
        public SetPolicyEvalValuesXmlRequest()
        {
        }
        
        public SetPolicyEvalValuesXmlRequest(string sUser, string sPassword, string sPolitica, string sParametros)
        {
            this.sUser = sUser;
            this.sPassword = sPassword;
            this.sPolitica = sPolitica;
            this.sParametros = sParametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPolicyEvalValuesXmlResponse", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class SetPolicyEvalValuesXmlResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string SetPolicyEvalValuesXmlResult;
        
        public SetPolicyEvalValuesXmlResponse()
        {
        }
        
        public SetPolicyEvalValuesXmlResponse(string SetPolicyEvalValuesXmlResult)
        {
            this.SetPolicyEvalValuesXmlResult = SetPolicyEvalValuesXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPolicyEvalValuesObjectXml", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class SetPolicyEvalValuesObjectXmlRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=0)]
        public string sUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=1)]
        public string sPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=2)]
        public string sPolitica;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/WCCrivo", Order=3)]
        public string sParametros;
        
        public SetPolicyEvalValuesObjectXmlRequest()
        {
        }
        
        public SetPolicyEvalValuesObjectXmlRequest(string sUser, string sPassword, string sPolitica, string sParametros)
        {
            this.sUser = sUser;
            this.sPassword = sPassword;
            this.sPolitica = sPolitica;
            this.sParametros = sParametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPolicyEvalValuesObjectXmlResponse", WrapperNamespace="http://tempuri.org/WCCrivo", IsWrapped=true)]
    public partial class SetPolicyEvalValuesObjectXmlResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.crivo.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="www.crivo.com.br", IsNullable=true)]
        public CreditTalk.ResultEvalValuesXml ResultadoXml;
        
        public SetPolicyEvalValuesObjectXmlResponse()
        {
        }
        
        public SetPolicyEvalValuesObjectXmlResponse(CreditTalk.ResultEvalValuesXml ResultadoXml)
        {
            this.ResultadoXml = ResultadoXml;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface CreditTalkStatelessSoapChannel : CreditTalk.CreditTalkStatelessSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class CreditTalkStatelessSoapClient : System.ServiceModel.ClientBase<CreditTalk.CreditTalkStatelessSoap>, CreditTalk.CreditTalkStatelessSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CreditTalkStatelessSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CreditTalkStatelessSoapClient.GetBindingForEndpoint(endpointConfiguration), CreditTalkStatelessSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditTalkStatelessSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CreditTalkStatelessSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditTalkStatelessSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CreditTalkStatelessSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditTalkStatelessSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CreditTalk.ReportResponse> ReportAsync(CreditTalk.ReportRequest request)
        {
            return base.Channel.ReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditTalk.ExplainResponse> ExplainAsync(CreditTalk.ExplainRequest request)
        {
            return base.Channel.ExplainAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditTalk.LoadPDFResponse> LoadPDFAsync(CreditTalk.LoadPDFRequest request)
        {
            return base.Channel.LoadPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditTalk.ValuesResponse> ValuesAsync(CreditTalk.ValuesRequest request)
        {
            return base.Channel.ValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditTalk.LayoutResponse> LayoutAsync(CreditTalk.LayoutRequest request)
        {
            return base.Channel.LayoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditTalk.ParametersResponse> ParametersAsync(CreditTalk.ParametersRequest request)
        {
            return base.Channel.ParametersAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditTalk.RawDataResponse> RawDataAsync(CreditTalk.RawDataRequest request)
        {
            return base.Channel.RawDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditTalk.SourcesResponse> SourcesAsync(CreditTalk.SourcesRequest request)
        {
            return base.Channel.SourcesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditTalk.LoadLogResponse> LoadLogAsync(CreditTalk.LoadLogRequest request)
        {
            return base.Channel.LoadLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditTalk.EvalResponse> EvalAsync(CreditTalk.EvalRequest request)
        {
            return base.Channel.EvalAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditTalk.SetPolicyEvalResponse> SetPolicyEvalAsync(CreditTalk.SetPolicyEvalRequest request)
        {
            return base.Channel.SetPolicyEvalAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditTalk.SetPolicyEvalValuesResponse> SetPolicyEvalValuesAsync(CreditTalk.SetPolicyEvalValuesRequest request)
        {
            return base.Channel.SetPolicyEvalValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditTalk.SetPolicyEvalValuesXmlResponse> SetPolicyEvalValuesXmlAsync(CreditTalk.SetPolicyEvalValuesXmlRequest request)
        {
            return base.Channel.SetPolicyEvalValuesXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditTalk.SetPolicyEvalValuesObjectXmlResponse> SetPolicyEvalValuesObjectXmlAsync(CreditTalk.SetPolicyEvalValuesObjectXmlRequest request)
        {
            return base.Channel.SetPolicyEvalValuesObjectXmlAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CreditTalkStatelessSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditTalkStatelessSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CreditTalkStatelessSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://vmwgeraltst011.brazilsouth.cloudapp.azure.com/ws/CreditTalkStateless.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditTalkStatelessSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://vmwgeraltst011.brazilsouth.cloudapp.azure.com/ws/CreditTalkStateless.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CreditTalkStatelessSoap,
            
            CreditTalkStatelessSoap12,
        }
    }
}
